# Generated by Django 2.2.7 on 2019-12-17 18:30

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    atomic = False
    dependencies = [
        ('rank', '0002_auto_20191217_1326'),
    ]

    operations = [
        migrations.CreateModel(
            name='film',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=80)),
                ('rank', models.IntegerField()),
            ],
            options={
                'ordering': ['rank'],
            },
        ),
        migrations.RenameModel(
            old_name='lists',
            new_name='list',
        ),
        migrations.DeleteModel(
            name='films',
        ),
        migrations.AddField(
            model_name='film',
            name='post',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='film', to='rank.list'),
        ),
    ]
