# Generated by Django 2.2.7 on 2019-12-20 19:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rank', '0002_auto_20191220_1458'),
    ]

    operations = [
        migrations.AddConstraint(
            model_name='film',
            constraint=models.UniqueConstraint(fields=('parentRanking', 'name'), name='unique_film'),
        ),
    ]
