# Generated by Django 2.2.7 on 2019-12-17 18:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rank', '0003_auto_20191217_1330'),
    ]

    operations = [
        migrations.RenameField(
            model_name='film',
            old_name='post',
            new_name='list',
        ),
        migrations.AlterField(
            model_name='film',
            name='rank',
            field=models.IntegerField(unique=True),
        ),
    ]
