# Generated by Django 2.2.7 on 2019-12-17 19:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('rank', '0004_auto_20191217_1344'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='film',
            options={'ordering': ['list', 'rank']},
        ),
    ]
