# Generated by Django 2.2.7 on 2019-12-17 23:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rank', '0005_auto_20191217_1441'),
    ]

    operations = [
        migrations.AlterField(
            model_name='film',
            name='rank',
            field=models.IntegerField(),
        ),
        migrations.AddConstraint(
            model_name='film',
            constraint=models.UniqueConstraint(fields=('list', 'rank'), name='unique_rank'),
        ),
    ]
