# Generated by Django 2.2.7 on 2019-12-18 02:14

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('rank', '0007_auto_20191217_2114'),
    ]

    operations = [
        migrations.AlterField(
            model_name='film',
            name='list',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='film', to='rank.list'),
        ),
    ]
