# Generated by Django 2.2.7 on 2019-12-16 03:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='tags',
            field=models.CharField(default='Subotai54', max_length=200),
        ),
    ]
